// rankingData.js - Dados simples para o componente RankingSemanal

export const RANKING_DATA = {
  Geral: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 88,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 90,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 92,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user234",
      nome: "Ana Pereira",
      pontos: 85,
      posicaoAnterior: 5,
      foto: null,
      sexo: "Feminino",
      idade: 22,
    },
    {
      id: "user345",
      nome: "Carlos Ferreira",
      pontos: 82,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Masculino",
      idade: 45,
    },
    {
      id: "user567",
      nome: "Mariana Costa",
      pontos: 80,
      posicaoAnterior: 8,
      foto: null,
      sexo: "Feminino",
      idade: 19,
    },
    {
      id: "user678",
      nome: "Rafael Souza",
      pontos: 78,
      posicaoAnterior: 6,
      foto: null,
      sexo: "Masculino",
      idade: 36,
    },
    {
      id: "user890",
      nome: "Juliana Lima",
      pontos: 75,
      posicaoAnterior: 7,
      foto: null,
      sexo: "Feminino",
      idade: 31,
    },
    {
      id: "user901",
      nome: "Fernando Alves",
      pontos: 72,
      posicaoAnterior: 9,
      foto: null,
      sexo: "Masculino",
      idade: 62,
    },
    {
      id: "user012",
      nome: "Aline Martins",
      pontos: 70,
      posicaoAnterior: 10,
      foto: null,
      sexo: "Feminino",
      idade: 42,
    },
    {
      id: "user013",
      nome: "Roberto Lima",
      pontos: 68,
      posicaoAnterior: 11,
      foto: null,
      sexo: "Masculino",
      idade: 55,
    },
    {
      id: "user014",
      nome: "Carla Mendes",
      pontos: 66,
      posicaoAnterior: 12,
      foto: null,
      sexo: "Feminino",
      idade: 47,
    },
    {
      id: "user015",
      nome: "Gabriel Santos",
      pontos: 65,
      posicaoAnterior: 13,
      foto: null,
      sexo: "Masculino",
      idade: 18,
    },
    {
      id: "user016",
      nome: "Larissa Silva",
      pontos: 64,
      posicaoAnterior: 14,
      foto: null,
      sexo: "Feminino",
      idade: 16,
    },
    {
      id: "user017",
      nome: "Antônio Gomes",
      pontos: 62,
      posicaoAnterior: 15,
      foto: null,
      sexo: "Masculino",
      idade: 68,
    },
    {
      id: "user018",
      nome: "Helena Costa",
      pontos: 60,
      posicaoAnterior: 16,
      foto: null,
      sexo: "Feminino",
      idade: 71,
    },
  ],
  Peito: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 92,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 95,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 88,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user019",
      nome: "Miguel Teixeira",
      pontos: 87,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Masculino",
      idade: 24,
    },
    {
      id: "user020",
      nome: "Fernanda Ribeiro",
      pontos: 85,
      posicaoAnterior: 7,
      foto: null,
      sexo: "Feminino",
      idade: 26,
    },
  ],
  Costas: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 90,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 92,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 85,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user234",
      nome: "Ana Pereira",
      pontos: 88,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Feminino",
      idade: 22,
    },
    {
      id: "user345",
      nome: "Carlos Ferreira",
      pontos: 80,
      posicaoAnterior: 5,
      foto: null,
      sexo: "Masculino",
      idade: 45,
    },
    {
      id: "user567",
      nome: "Mariana Costa",
      pontos: 78,
      posicaoAnterior: 6,
      foto: null,
      sexo: "Feminino",
      idade: 19,
    },
    {
      id: "user678",
      nome: "Rafael Souza",
      pontos: 76,
      posicaoAnterior: 7,
      foto: null,
      sexo: "Masculino",
      idade: 36,
    },
    {
      id: "user890",
      nome: "Juliana Lima",
      pontos: 74,
      posicaoAnterior: 8,
      foto: null,
      sexo: "Feminino",
      idade: 31,
    },
    {
      id: "user901",
      nome: "Fernando Alves",
      pontos: 72,
      posicaoAnterior: 9,
      foto: null,
      sexo: "Masculino",
      idade: 62,
    },
  ],
  Braço: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 90,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 92,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 85,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user234",
      nome: "Ana Pereira",
      pontos: 88,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Feminino",
      idade: 22,
    },
    {
      id: "user345",
      nome: "Carlos Ferreira",
      pontos: 80,
      posicaoAnterior: 5,
      foto: null,
      sexo: "Masculino",
      idade: 45,
    },
    {
      id: "user021",
      nome: "Vinícius Cardoso",
      pontos: 79,
      posicaoAnterior: 8,
      foto: null,
      sexo: "Masculino",
      idade: 27,
    },
    {
      id: "user022",
      nome: "Camila Rocha",
      pontos: 77,
      posicaoAnterior: 6,
      foto: null,
      sexo: "Feminino",
      idade: 30,
    },
  ],
  Perna: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 90,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 92,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 85,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user023",
      nome: "Cristina Moraes",
      pontos: 84,
      posicaoAnterior: 5,
      foto: null,
      sexo: "Feminino",
      idade: 33,
    },
    {
      id: "user024",
      nome: "Rodrigo Fernandes",
      pontos: 82,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Masculino",
      idade: 29,
    },
  ],
  Ombro: [
    {
      id: "user123",
      nome: "João Santos",
      pontos: 90,
      posicaoAnterior: 1,
      foto: null,
      sexo: "Masculino",
      idade: 28,
    },
    {
      id: "user456",
      nome: "Pedro Oliveira",
      pontos: 92,
      posicaoAnterior: 2,
      foto: null,
      sexo: "Masculino",
      idade: 32,
    },
    {
      id: "user789",
      nome: "Maria Silva",
      pontos: 85,
      posicaoAnterior: 3,
      foto: null,
      sexo: "Feminino",
      idade: 29,
    },
    {
      id: "user234",
      nome: "Ana Pereira",
      pontos: 88,
      posicaoAnterior: 4,
      foto: null,
      sexo: "Feminino",
      idade: 22,
    },
    {
      id: "user345",
      nome: "Carlos Ferreira",
      pontos: 80,
      posicaoAnterior: 5,
      foto: null,
      sexo: "Masculino",
      idade: 45,
    },
  ],
};

export const SEXOS = [
  { id: "Masculino", label: "Masculino", color: "sky" },
  { id: "Feminino", label: "Feminino", color: "pink" },
];

export const FAIXAS_ETARIAS = [
  { id: "10-20", label: "10-20 anos", range: { min: 10, max: 20 } },
  { id: "20-40", label: "20-40 anos", range: { min: 20, max: 40 } },
  { id: "40-60", label: "40-60 anos", range: { min: 40, max: 60 } },
  { id: "60+", label: "60+ anos", range: { min: 60, max: 999 } },
];

export const CATEGORY_ICONS = {
  Peito: "peito.png",
  Perna: "perna.png",
  Ombro: "ombro.png",
  Costas: "costas.png",
  Braço: "musculo.png",
  Geral: "trophy",
};
