function Exercicios(props) {}
const [exercicios, setExercicios] = useState([
  {
    id: 1,
    nome: "Supino Reto",
    grupoMuscular: "Peitoral",
    series: 4,
    repeticoes: 10,
    carga: 30,
  },
  {
    id: 2,
    nome: "Supino Inclinado",
    grupoMuscular: "Peitoral",
    series: 4,
    repeticoes: 10,
    carga: 25,
  },
  {
    id: 3,
    nome: "Crucifixo",
    grupoMuscular: "Peitoral",
    series: 3,
    repeticoes: 12,
    carga: 15,
  },
  {
    id: 4,
    nome: "Peck Deck",
    grupoMuscular: "Peitoral",
    series: 4,
    repeticoes: 10,
    carga: 40,
  },
  {
    id: 5,
    nome: "Crossover",
    grupoMuscular: "Peitoral",
    series: 3,
    repeticoes: 12,
    carga: 20,
  },
  {
    id: 6,
    nome: "Flexão de Braço",
    grupoMuscular: "Peitoral",
    series: 3,
    repeticoes: 15,
    carga: 0,
  },
  {
    id: 7,
    nome: "Barra Fixa",
    grupoMuscular: "Costas",
    series: 4,
    repeticoes: 8,
    carga: 0,
  },
  {
    id: 8,
    nome: "Puxador Frontal",
    grupoMuscular: "Costas",
    series: 4,
    repeticoes: 10,
    carga: 50,
  },
  {
    id: 9,
    nome: "Remada Curvada",
    grupoMuscular: "Costas",
    series: 4,
    repeticoes: 10,
    carga: 40,
  },
  {
    id: 10,
    nome: "Remada Baixa",
    grupoMuscular: "Costas",
    series: 4,
    repeticoes: 10,
    carga: 45,
  },
  {
    id: 11,
    nome: "Pulldown",
    grupoMuscular: "Costas",
    series: 3,
    repeticoes: 12,
    carga: 35,
  },
  {
    id: 12,
    nome: "Levantamento Terra",
    grupoMuscular: "Costas",
    series: 4,
    repeticoes: 8,
    carga: 60,
  },
  {
    id: 13,
    nome: "Rosca Direta",
    grupoMuscular: "Braço",
    series: 4,
    repeticoes: 10,
    carga: 20,
  },
  {
    id: 14,
    nome: "Rosca Martelo",
    grupoMuscular: "Braço",
    series: 4,
    repeticoes: 10,
    carga: 20,
  },
  {
    id: 15,
    nome: "Rosca Concentrada",
    grupoMuscular: "Braço",
    series: 3,
    repeticoes: 12,
    carga: 15,
  },
  {
    id: 16,
    nome: "Tríceps Testa",
    grupoMuscular: "Braço",
    series: 4,
    repeticoes: 10,
    carga: 25,
  },
  {
    id: 17,
    nome: "Tríceps Francês",
    grupoMuscular: "Braço",
    series: 4,
    repeticoes: 10,
    carga: 20,
  },
  {
    id: 18,
    nome: "Tríceps Corda",
    grupoMuscular: "Braço",
    series: 4,
    repeticoes: 12,
    carga: 30,
  },
  {
    id: 19,
    nome: "Agachamento Livre",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 10,
    carga: 60,
  },
  {
    id: 20,
    nome: "Leg Press",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 10,
    carga: 100,
  },
  {
    id: 21,
    nome: "Cadeira Extensora",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 12,
    carga: 50,
  },
  {
    id: 22,
    nome: "Flexora",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 12,
    carga: 40,
  },
  {
    id: 23,
    nome: "Levantamento Terra",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 8,
    carga: 70,
  },
  {
    id: 24,
    nome: "Panturrilha em Pé",
    grupoMuscular: "Pernas",
    series: 4,
    repeticoes: 15,
    carga: 30,
  },
  {
    id: 25,
    nome: "Desenvolvimento com Halteres",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 10,
    carga: 25,
  },
  {
    id: 26,
    nome: "Elevação Lateral",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 12,
    carga: 15,
  },
  {
    id: 27,
    nome: "Elevação Frontal",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 12,
    carga: 15,
  },
  {
    id: 28,
    nome: "Remada Alta",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 10,
    carga: 30,
  },
  {
    id: 29,
    nome: "Desenvolvimento Máquina",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 10,
    carga: 40,
  },
  {
    id: 30,
    nome: "Encolhimento de Ombros",
    grupoMuscular: "Ombros",
    series: 4,
    repeticoes: 12,
    carga: 35,
  },
]);
